defaults: &defaults
  booking_base_uri: "http://192.168.31.4:9001"
  booking_user: test
  booking_password: test

  expedia_base_uri: "http://192.168.31.4:9001"
  expedia_user: test
  expedia_password: test

  worker_interval: 120

development:
  <<: *defaults

test:
  <<: *defaults

production:
  booking_base_uri: "http://127.0.0.1/"
  booking_user: test
  booking_password: test

  expedia_base_uri: "https://services.expediapartnercentral.com"
  expedia_user: <%= ENV.fetch("EXPEDIA_USR") { 'testuser' } %>
  expedia_password: <%= ENV.fetch("EXPEDIA_PWD") { 'testpass' } %>
  worker_interval: 240